// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9vNGKFiuISyur16ZZCyK_42GV1uvzXZw',
    appId: '1:512286530594:web:c75c88c3c4db6548707e7b',
    messagingSenderId: '512286530594',
    projectId: 'liftlink-c1d90',
    authDomain: 'liftlink-c1d90.firebaseapp.com',
    storageBucket: 'liftlink-c1d90.appspot.com',
    measurementId: 'G-ZJEHX93FNC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWKTqROuFkpqWVsRx55rQJswlfNC5F4Kc',
    appId: '1:512286530594:android:227551dd2e21cdcf707e7b',
    messagingSenderId: '512286530594',
    projectId: 'liftlink-c1d90',
    storageBucket: 'liftlink-c1d90.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwwsrEuOq1eiHMI8uz70HEoPIl765PU70',
    appId: '1:512286530594:ios:3c4bc1fbd89ca78a707e7b',
    messagingSenderId: '512286530594',
    projectId: 'liftlink-c1d90',
    storageBucket: 'liftlink-c1d90.appspot.com',
    androidClientId: '512286530594-g2gpnlodbght9fjrnui8v5b8bm657a9d.apps.googleusercontent.com',
    iosClientId: '512286530594-0081gv9m79rustfrfbuf6jt84annd1lv.apps.googleusercontent.com',
    iosBundleId: 'com.example.liftlink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwwsrEuOq1eiHMI8uz70HEoPIl765PU70',
    appId: '1:512286530594:ios:567393f4f0244262707e7b',
    messagingSenderId: '512286530594',
    projectId: 'liftlink-c1d90',
    storageBucket: 'liftlink-c1d90.apps pot.com',
    androidClientId: '512286530594-g2gpnlodbght9fjrnui8v5b8bm657a9d.apps.googleusercontent.com',
    iosClientId: '512286530594-iilgngtl6f78d5hvtel9vqub0bsvptli.apps.googleusercontent.com',
    iosBundleId: 'com.example.liftlink.RunnerTests',
  );
}
